# pytest.ini
# Run tests with: pytest -v

[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests/test_*.py
python_classes = *Test
python_functions = test_*
addopts =
    --reuse-db
    -v
    --tb=short
